;; Q: Draw a tree illustrating the process generated by count-change from section 1.2.2 in making change for 11 cents.
;; What are the orders of growth of space and number of steps as the amount of change increases.

;; Here's count change.

(define (cc amount kinds-of-coins)
  (cond ((= amount 0) 1)
        ((or (< amount 0) (= kinds-of-coins 0)) 0)
        (else (+ (cc amount
                     (- kinds-of-coins 1))
                 (cc (- amount
                        (first-denomination kinds-of-coins))
                     kinds-of-coins)))))

(define (first-denomination kinds-of-coins)
  (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)))

(define (count-change amount)
  (cc amount 5))

(count-change 100) ;; 292

;; I roughly drew this tree out, it's in images/counting-change.jpg
;; Space usage is O(n) because the depth of the tree is determined by the inputs.
;; Steps were harder, I originally assumed O(n^2) because each node splits into two, but that's not right.
;; It's really O(n^c) where c is the number of coins. So for this one, it is O(n^5)
