;; Q: Draw a tree illustrating the process generated by count-change from section 1.2.2 in making change for 11 cents.
;; What are the orders of growth of space and number of steps as the amount of change increases.

;; Here's count change.

(define (cc amount kinds-of-coins)
  (cond ((= amount 0) 1)
        ((or (< amount 0) (= kinds-of-coins 0)) 0)
        (else (+ (cc amount
                     (- kinds-of-coins 1))
                 (cc (- amount
                        (first-denomination kinds-of-coins))
                     kinds-of-coins)))))

(define (first-denomination kinds-of-coins)
  (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)))

(define (count-change amount)
  (cc amount 5))

(count-change 100) ;; 292

;; Here's the tree for 11 cents.

----

                         11,5
                   11,4         -39,5
             11,3       -14,4     =0
        11,2       1,3
    11,1
11,0
 =0
