;; Q: Illustrate the process generated by (gcd 206 40), indicating remainder operations performed.
;; How many remainder operations are performed in a normal and applicative order evaluation.

(define (gcd a b)
  (if (= b 0)
      a
      (gcd b (remainder a b))))

;; Applicative: 4

(gcd 206 40)
(gcd 40 (remainder 206 40)) ;; 6
(gcd 40 (remainder 40 6)) ;; 4
(gcd 6 (remainder 6 4)) ;; 2
(gcd 4 (remainder 4 2)) ;; 0
2

;; Normal: 18
;; Why is it called normal when it's so weird? Was it "normal" back then?
;; Was Scheme the thing pushing the boundaries here too?

;; I can't visualise these steps in my head, it's 18 though.
